DROP TABLE IF EXISTS requests, comments,bookings,items, users;


CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description varchar(200) NOT NULL,
    requestor_id bigint,
    created TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_requests PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS Items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id bigint,
    name varchar(200) NOT NULL,
    description varchar(200) NOT NULL,
    available boolean,
    request_id bigint,
    CONSTRAINT pk_items PRIMARY KEY (id),
    CONSTRAINT fk_owner_id FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT fk_request_id FOREIGN KEY (request_id) REFERENCES requests (id)
    );

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date TIMESTAMP WITHOUT TIME ZONE,
    item_id bigint NOT NULL,
    booker_id bigint NOT NULL,
    status varchar(200),
    CONSTRAINT fk_booking_booker_id FOREIGN KEY (booker_id) REFERENCES users (id),
    CONSTRAINT  fk_item_id FOREIGN KEY (item_id) REFERENCES Items (id)
    );

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text varchar(200) NOT NULL,
    item_id bigint,
    author_id bigint,
    created TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT fk_author_id FOREIGN KEY (author_id) REFERENCES users (id),
    CONSTRAINT  fk_comment_item_id FOREIGN KEY (item_id) REFERENCES Items (id)
    );